name: RunTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    
    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
          - 4569:4569
    steps:
      - uses: actions/checkout@v2
      - name: Install unzip and python
        run: |
          apt update && apt install git unzip python python3 curl build-essential -y
      - name: Install node
        run: |
          curl -fsSL https://deb.nodesource.com/setup_15.x | bash
          apt-get install -y nodejs
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15' 
      - uses: hashicorp/setup-terraform@v1
        with:
           terraform_version: 0.13
           terraform_wrapper: false
      - name: Run the tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: cd ./test && go test -v
     
